### ISSUE TITLE
Not sure what I'm doing wrong here...?

### ISSUE THREAD

**Issue by ianwesty** [sklise/hubot-web#3]
Hi, I am having some trouble implementing your adaptor.

I have defined a url to post the response (HUBOT_REST_SEND_URL) to, but nothing is being received.

My understanding is that if I run a command like `hubot ping` for example, it will post the response to HUBOT_REST_SEND_URL?

How do I interactive with the adaptor, as the CLI functionality does not work as soon as I run `bin/hubot -a web`?

**Comment by sklise** [comment]
Launching hubot with `bin/hubot -a web` will start up a webserver on your localhost. You need to have a `PORT` variable set in your ENV.

If you set `PORT=3030` then a `curl -X POST http://localhost:3030/receive/general` request will send a message to Hubot. And if Hubot chooses to respond, Hubot will send a post to `HUBOT_REST_SEND_URL`
